CREATE DATABASE IF NOT EXISTS email_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE email_system;

CREATE TABLE IF NOT EXISTS emails (
    no INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
